Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2021-05, with the labels that each got.

#445 Added ubuntu 18.04 docker image for ML.NET
  manifest.json
  src/ubuntu/18.04/mlnet/Dockerfile
Labels: area-dockerfiles

#447 mlnet cross targeting images
  manifest.json
  src/ubuntu/18.04/mlnet/cross/arm/Dockerfile
  src/ubuntu/18.04/mlnet/cross/arm/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm/hooks/pre-build
  src/ubuntu/18.04/mlnet/cross/arm64/Dockerfile
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/pre-build
Labels: area-dockerfiles

#449 Remove usage of Windows Server, version 1909
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-1909-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-1909.yml
  manifest.json
  src/windowsservercore/1909/helix/amd64/Dockerfile
Labels: area-documentation

#450 [wasm] Bump emscripten version to 2.0.21
  src/ubuntu/18.04/webassembly/Dockerfile
  src/windowsservercore/2004/helix/webassembly/Dockerfile
Labels: area-documentation

#453 Introduce a CBL Mariner image for Helix .NET Core Testing
  eng/pipelines/dotnet-buildtools-prereqs-mariner-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-mariner.yml
  manifest.json
  src/cbl-mariner/1.0/helix/amd64/Dockerfile
Labels: area-dockerfiles

#455 Added dockerfiles for ml.net on helix.
  manifest.json
  src/centos/7/mlnet/helix/Dockerfile
  src/ubuntu/16.04/mlnet/helix/Dockerfile
Labels: area-dockerfiles

#456 Add some dependencies into the Helix Mariner image
  src/cbl-mariner/1.0/helix/amd64/Dockerfile
Labels: area-dockerfiles

#459 Add iputils, tzdata, and microsoft CA packages (needed by runtime tests) to Mariner image
  src/cbl-mariner/1.0/helix/amd64/Dockerfile
Labels: area-infrastructure

#458 [wasm] Bump emscripten version to 2.0.23
  src/ubuntu/18.04/webassembly/Dockerfile
  src/windowsservercore/2004/helix/webassembly/Dockerfile
Labels: area-documentation
