Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2021-12, with the labels that each got.

#543 Create Alpine 3.15 images
  manifest.json
  src/alpine/3.10/helix/amd64/Dockerfile
  src/alpine/3.10/helix/arm64v8/Dockerfile
  src/alpine/3.15/WithNode/amd64/Dockerfile
  src/alpine/3.15/amd64/Dockerfile
  src/alpine/3.15/helix/amd64/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/alpine/3.9/WithNode/amd64/Dockerfile
  src/alpine/3.9/arm32v7/Dockerfile
  src/alpine/3.9/arm64v8/Dockerfile
  src/alpine/3.9/helix/amd64/Dockerfile
Labels: area-dockerfiles

#548 Bump emscripten version to 2.0.34
  src/ubuntu/18.04/webassembly/Dockerfile
  src/windowsservercore/2004/helix/webassembly/Dockerfile
Labels: area-documentation

#547 Add an Ubuntu 20.04 image for building against Raspbian 10
  manifest.json
  src/ubuntu/20.04/coredeps/Dockerfile
  src/ubuntu/20.04/cross/armv6/10/Dockerfile
  src/ubuntu/20.04/cross/armv6/10/hooks/post-build
  src/ubuntu/20.04/cross/armv6/10/hooks/pre-build
  src/ubuntu/20.04/crossdeps/Dockerfile
Labels: area-infrastructure

#545 Disable Kusto ingestion during publish
  eng/pipelines/variables/common.yml
Labels: area-infrastructure

#552 Consolidate pipelines into a per-OS grouping
  README.md
  eng/pipelines/dotnet-buildtools-prereqs-centos-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos-stream9.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos7-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos7.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos8.yml
  eng/pipelines/dotnet-buildtools-prereqs-nanoserver-1809.yml
  eng/pipelines/dotnet-buildtools-prereqs-nanoserver-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-nanoserver.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu16-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu18-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu18.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu20-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu20.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu21.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-2004.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-20H2-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-20H2.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore.yml
  manifest.json
  src/alpine/manifest.json
  src/cbl-mariner/manifest.json
  src/centos/manifest.json
  src/debian/9/amd64/Dockerfile
  src/debian/manifest.json
  src/fedora/manifest.json
  src/nanoserver/manifest.json
  src/opensuse/manifest.json
  src/ubuntu/manifest.json
  src/windowsservercore/manifest.json
Labels: area-infrastructure

#550 Raspbian helix image
  eng/common/templates/stages/build-test-publish-repo.yml
  eng/pipelines/dotnet-buildtools-prereqs-raspbian-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-raspbian.yml
  eng/pipelines/steps/install-cross-build-prereqs.yml
  manifest.json
  src/raspbian/10/crossdeps/Dockerfile
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/raspbian/10/helix/arm32v6/hooks/post-build
  src/raspbian/10/helix/arm32v6/hooks/pre-build
  src/raspbian/manifest.json
  src/ubuntu/build-scripts/build-rootfs.sh
Labels: area-infrastructure
