Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2021-07, with the labels that each got.

#469 [wasm] Add arial font for chrome
  src/windowsservercore/2004/helix/webassembly/Dockerfile
  src/windowsservercore/2004/helix/webassembly/hooks/pre-build.ps1
Labels: area-samples

#475 make ping suid so helix user can run it
  src/fedora/32/helix/amd64/Dockerfile
Labels: area-infrastructure

#476 [wasm] Install 7z in windows helix image
  src/windowsservercore/2004/helix/webassembly/Dockerfile
Labels: area-samples

#446 Add lld linker to the centos, alpine and crossbuild images
  eng/pipelines/dotnet-buildtools-prereqs-centos7-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos7.yml
  src/alpine/3.13/WithNode/amd64/Dockerfile
  src/alpine/3.9/WithNode/amd64/Dockerfile
  src/alpine/3.9/amd64/Dockerfile
  src/centos/7/Dockerfile
  src/centos/7/rpmpkg/Dockerfile
  src/centos/8/Dockerfile
  src/ubuntu/18.04/crossdeps/Dockerfile
Labels: area-dockerfiles

#480 Add lld into Ubuntu 16.04 cross images
  src/ubuntu/16.04/coredeps/Dockerfile
  src/ubuntu/16.04/cross/arm64/Dockerfile
  src/ubuntu/16.04/crossdeps/Dockerfile
Labels: area-dockerfiles

#479 Add lldb to alpine 3.12/3.13 images
  src/alpine/3.12/helix/amd64/Dockerfile
  src/alpine/3.13/amd64/Dockerfile
Labels: area-dockerfiles

#481 [dotnet\runtime WASM] Added typescript
  src/ubuntu/18.04/webassembly/Dockerfile
Labels: area-dockerfiles

#478 Add armel-tizen
  manifest.json
  src/ubuntu/18.04/cross/armel-tizen/Dockerfile
  src/ubuntu/18.04/cross/armel-tizen/hooks/post-build
  src/ubuntu/18.04/cross/armel-tizen/hooks/pre-build
  src/ubuntu/18.04/crossdeps/Dockerfile
  src/ubuntu/build-scripts/build-rootfs.sh
Labels: area-dockerfiles

#482 Fix node path in AzDO agent label for Alpine 3.13 with node image
  src/alpine/3.13/WithNode/amd64/Dockerfile
Labels: area-infrastructure

#487 Symlink post-build hooks and quote strings
  src/ubuntu/18.04/cross/s390x/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/post-build
  src/ubuntu/build-scripts/build-rootfs.sh
Labels: area-infrastructure

#486 disable Fedora rawhide
  manifest.json
Labels: area-dockerfiles

#485 Add the lldb python support to Alpine 3.12/3.13
  src/alpine/3.12/helix/amd64/Dockerfile
  src/alpine/3.13/amd64/Dockerfile
Labels: area-infrastructure

#488 small fixes for Fedora34 helix image
  src/fedora/34/helix/amd64/Dockerfile
Labels: area-infrastructure

#489 Delete Fedora rawhide Dockerfile
  src/fedora/rawhide/amd64/Dockerfile
Labels: area-infrastructure
