Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2022-09, with the labels that each got.

#683 Fix codename in riscv64 pre-build hook
  src/ubuntu/22.04/cross/riscv64/hooks/pre-build
Labels: area-infrastructure

#681 Add python-pip3 to the list of Ubuntu apt package dependencies
  src/ubuntu/18.04/coredeps/Dockerfile
  src/ubuntu/20.04/coredeps/Dockerfile
  src/ubuntu/22.04/coredeps/Dockerfile
Labels: area-dockerfiles

#688 update Fedora image to have msquic 2.1.1
  src/fedora/34/helix/amd64/Dockerfile
  src/fedora/36/helix/amd64/Dockerfile
Labels: area-dockerfiles

#687 update msquic to 2.1.1 for Ubuntu arm64
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-dockerfiles

#689 add msquic 2.1.1 to Debian arm32 images
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
Labels: area-dockerfiles

#691 Add additional packages for centos-stream9-helix
  src/centos/stream9/helix/amd64/Dockerfile
Labels: area-infrastructure

#667 Add latest/staging tag to all docker images
  build.ps1
  eng/pipelines/dotnet-buildtools-prereqs-alpine-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-alpine.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos.yml
  eng/pipelines/dotnet-buildtools-prereqs-debian-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-debian.yml
  eng/pipelines/dotnet-buildtools-prereqs-eng.yml
  eng/pipelines/dotnet-buildtools-prereqs-fedora-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-fedora.yml
  eng/pipelines/dotnet-buildtools-prereqs-mariner-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-mariner.yml
  eng/pipelines/dotnet-buildtools-prereqs-nanoserver-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-nanoserver.yml
  eng/pipelines/dotnet-buildtools-prereqs-opensuse-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-opensuse.yml
  eng/pipelines/dotnet-buildtools-prereqs-raspbian-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-raspbian.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-windowsservercore.yml
  eng/pipelines/variables/common.yml
  src/alpine/manifest.json
  src/cbl-mariner/manifest.json
  src/centos/manifest.json
  src/debian/manifest.json
  src/fedora/manifest.json
  src/nanoserver/manifest.json
  src/opensuse/manifest.json
  src/raspbian/manifest.json
  src/ubuntu/manifest.json
  src/windowsservercore/manifest.json
Labels: area-dockerfiles

#693 Add production as an official branch
  eng/pipelines/variables/common.yml
Labels: area-documentation

#697 Rename build-rootfs to run-arcade-build-rootfs
  src/raspbian/10/helix/arm32v6/hooks/pre-build
  src/ubuntu/18.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/18.04/cross/arm/hooks/pre-build
  src/ubuntu/18.04/cross/arm64-alpine/hooks/pre-build
  src/ubuntu/18.04/cross/arm64/hooks/pre-build
  src/ubuntu/18.04/cross/armel-tizen/hooks/pre-build
  src/ubuntu/18.04/cross/freebsd-arm64/13/hooks/pre-build
  src/ubuntu/18.04/cross/freebsd/12/hooks/pre-build
  src/ubuntu/18.04/cross/hooks/pre-build
  src/ubuntu/18.04/cross/illumos/hooks/pre-build
  src/ubuntu/18.04/cross/ppc64le/hooks/pre-build
  src/ubuntu/18.04/cross/s390x/hooks/pre-build
  src/ubuntu/18.04/cross/x86-linux/hooks/pre-build
  src/ubuntu/18.04/mlnet/cross/arm/hooks/pre-build
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/pre-build
  src/ubuntu/20.04/cross/armv6/10/hooks/pre-build
  src/ubuntu/22.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/arm/hooks/pre-build
  src/ubuntu/22.04/cross/arm64-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/arm64/hooks/pre-build
  src/ubuntu/22.04/cross/haiku/hooks/pre-build
  src/ubuntu/22.04/cross/riscv64/hooks/pre-build
  src/ubuntu/build-scripts/run-arcade-build-rootfs.sh
Labels: area-infrastructure

#704 Only use floating tag suffix for staging
  eng/pipelines/variables/common.yml
  src/alpine/manifest.json
  src/cbl-mariner/manifest.json
  src/centos/manifest.json
  src/debian/manifest.json
  src/fedora/manifest.json
  src/nanoserver/manifest.json
  src/opensuse/manifest.json
  src/raspbian/manifest.json
  src/ubuntu/manifest.json
  src/windowsservercore/manifest.json
Labels: area-infrastructure
