Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2022-12, with the labels that each got.

#746 Fix WSC manifest to have separate images
  src/windowsservercore/manifest.json
Labels: area-infrastructure

#748 Fix cross root package sources for x86 ubuntu 18.04
  src/ubuntu/18.04/cross/x86-linux/hooks/pre-build
Labels: area-dockerfiles

#747 [Rollout] Production Rollout 2022-12-07
  eng/common/Get-ImageBuilder.ps1
  eng/common/Get-ImageNameVars.ps1
  eng/common/Install-DotNetSdk.ps1
  eng/common/Invoke-CleanupDocker.ps1
  eng/common/Invoke-ImageBuilder.ps1
  eng/common/templates/stages/build-test-publish-repo.yml
  eng/common/templates/steps/parse-test-arg-arrays.yml
  eng/common/templates/steps/test-images-linux-client.yml
  eng/common/templates/steps/test-images-windows-client.yml
  eng/common/templates/variables/docker-images.yml
  src/ubuntu/20.04/webassembly/Dockerfile
  src/ubuntu/manifest.json
Labels: area-documentation
