Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2022-05, with the labels that each got.

#612 Creating a 20.04 helix container
  src/ubuntu/20.04/helix/amd64/Dockerfile
  src/ubuntu/20.04/helix/wasm/amd64/Dockerfile
  src/ubuntu/manifest.json
Labels: area-documentation

#614 Different images to build and run wasm
  src/ubuntu/18.04/helix/webassembly/Dockerfile
  src/ubuntu/18.04/webassembly/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles

#610 Update centos7 rpmpkg to use ruby 2.5
  src/centos/7/rpmpkg/Dockerfile
Labels: area-samples

#616 Upgrade gcc:11 to gcc:12
  src/debian/11/gcc12/Dockerfile
  src/debian/manifest.json
Labels: area-dockerfiles

#615 Add Mariner 2.0 variant
  src/cbl-mariner/2.0/amd64/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-infrastructure

#602 Build Fedora 36 with msquic
  src/fedora/36/amd64/Dockerfile
  src/fedora/36/amd64/microsoft.asc
  src/fedora/36/helix/amd64/Dockerfile
  src/fedora/manifest.json
Labels: area-infrastructure

#619 Remove Fedora 33 Dockerfiles
  src/fedora/33/amd64/Dockerfile
  src/fedora/33/helix/amd64/Dockerfile
  src/fedora/manifest.json
Labels: area-dockerfiles

#622 Remove CentOS 8 Dockerfiles
  src/centos/8/Dockerfile
  src/centos/8/helix/amd64/Dockerfile
  src/centos/8/rpmpkg/Dockerfile
  src/centos/8/source-build/Dockerfile
  src/centos/manifest.json
Labels: area-dockerfiles
