Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2022-10, with the labels that each got.

#714 update msquic to 2.1.2 on arm32
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
Labels: area-infrastructure

#713 Update Android SDK
  src/ubuntu/18.04/android/Dockerfile
Labels: area-dockerfiles

#715 Add powershell to base ubuntu 18:04
  src/ubuntu/18.04/amd64/Dockerfile
Labels: area-dockerfiles

#708 Remove repo specifier from arm dockerfiles and registry from fedora
  src/alpine/3.13/helix/arm32v7/Dockerfile
  src/alpine/3.13/helix/arm64v8/Dockerfile
  src/alpine/3.14/helix/arm32v7/Dockerfile
  src/alpine/3.14/helix/arm64v8/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/debian/10/docker-testrunner/arm64v8/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
  src/debian/11/arm64v8/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/11/opt/arm64v8/Dockerfile
  src/debian/9/arm32v7/Dockerfile
  src/debian/9/arm64v8/Dockerfile
  src/debian/9/helix/arm32v7/Dockerfile
  src/debian/9/helix/arm64v8/Dockerfile
  src/debian/iot/arm32v7/Dockerfile
  src/fedora/34/amd64/Dockerfile
  src/fedora/36/amd64/Dockerfile
  src/raspbian/10/crossdeps/Dockerfile
  src/ubuntu/18.04/arm32v7/Dockerfile
  src/ubuntu/18.04/arm64v8/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/18.04/mono/arm32v7/Dockerfile
  src/ubuntu/18.04/mono/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-infrastructure

#710 General-purpose pipeline capable of building any path in the repo
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
Labels: area-infrastructure

#716 [Rollout] Production rollout, 2022-10-05
  src/alpine/3.13/helix/arm32v7/Dockerfile
  src/alpine/3.13/helix/arm64v8/Dockerfile
  src/alpine/3.14/helix/arm32v7/Dockerfile
  src/alpine/3.14/helix/arm64v8/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/debian/10/docker-testrunner/arm64v8/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
  src/debian/11/arm64v8/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/11/opt/arm64v8/Dockerfile
  src/debian/9/arm32v7/Dockerfile
  src/debian/9/arm64v8/Dockerfile
  src/debian/9/helix/arm32v7/Dockerfile
  src/debian/9/helix/arm64v8/Dockerfile
  src/debian/iot/arm32v7/Dockerfile
  src/fedora/34/amd64/Dockerfile
  src/fedora/36/amd64/Dockerfile
  src/raspbian/10/crossdeps/Dockerfile
  src/ubuntu/18.04/amd64/Dockerfile
  src/ubuntu/18.04/android/Dockerfile
  src/ubuntu/18.04/arm32v7/Dockerfile
  src/ubuntu/18.04/arm64v8/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/18.04/mono/arm32v7/Dockerfile
  src/ubuntu/18.04/mono/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-dockerfiles

#722 Remove end-of-life fedora images
  src/fedora/34/amd64/Dockerfile
  src/fedora/34/amd64/microsoft.asc
  src/fedora/34/helix/amd64/Dockerfile
  src/fedora/manifest.json
Labels: area-dockerfiles

#721 Remove eol debian dockerfiles and update base images
  src/debian/11/amd64/Dockerfile
  src/debian/11/arm64v8/Dockerfile
  src/debian/11/iot/arm32v7/Dockerfile
  src/debian/9/amd64/Dockerfile
  src/debian/9/arm32v7/Dockerfile
  src/debian/9/arm64v8/Dockerfile
  src/debian/9/helix/arm32v7/Dockerfile
  src/debian/9/helix/arm64v8/Dockerfile
  src/debian/manifest.json
Labels: area-dockerfiles

#725 Add secondary helixbot user to all helix ARM images;
  src/alpine/3.13/helix/arm32v7/Dockerfile
  src/alpine/3.13/helix/arm64v8/Dockerfile
  src/alpine/3.14/helix/arm32v7/Dockerfile
  src/alpine/3.14/helix/arm64v8/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-samples

#726 [Rollouts] Production Rollout, 2022-10-19
  eng/common/templates/stages/build-test-publish-repo.yml
  eng/common/templates/variables/docker-images.yml
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
  eng/pipelines/dotnet-buildtools-prereqs-alpine.yml
  eng/pipelines/dotnet-buildtools-prereqs-centos.yml
  eng/pipelines/dotnet-buildtools-prereqs-debian.yml
  eng/pipelines/dotnet-buildtools-prereqs-fedora.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu.yml
  eng/pipelines/steps/set-base-image-override-options.yml
  eng/pipelines/variables/common.yml
  src/alpine/3.13/helix/arm32v7/Dockerfile
  src/alpine/3.13/helix/arm64v8/Dockerfile
  src/alpine/3.14/helix/arm32v7/Dockerfile
  src/alpine/3.14/helix/arm64v8/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
  src/debian/11/amd64/Dockerfile
  src/debian/11/arm64v8/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/11/iot/arm32v7/Dockerfile
  src/debian/9/amd64/Dockerfile
  src/debian/9/arm32v7/Dockerfile
  src/debian/9/arm64v8/Dockerfile
  src/debian/9/helix/arm32v7/Dockerfile
  src/debian/9/helix/arm64v8/Dockerfile
  src/debian/manifest.json
  src/fedora/34/amd64/Dockerfile
  src/fedora/34/amd64/microsoft.asc
  src/fedora/34/helix/amd64/Dockerfile
  src/fedora/manifest.json
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-documentation

#718 Add rh-ruby binaries to path on centos-7-rpmpkg
  src/centos/7/rpmpkg/Dockerfile
  src/centos/7/rpmpkg/scl_enable
Labels: area-infrastructure

#729 [Rollouts] Production Rollout, 2022-10-26
  src/centos/7/rpmpkg/Dockerfile
  src/centos/7/rpmpkg/scl_enable
  src/ubuntu/18.04/amd64/Dockerfile
Labels: area-documentation
