Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-03, with the labels that each got.

#815 Use same rootfs in Ubuntu 22 cross arm64 as 18
  src/ubuntu/22.04/cross/arm64/Dockerfile
  src/ubuntu/22.04/cross/arm64/hooks/pre-build
Labels: area-dockerfiles

#819 fix failing pip on Debian 12
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
Labels: area-infrastructure

#818 update Alpine 3.15 Helix images
  src/alpine/3.15/helix/amd64/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
Labels: area-dockerfiles

#820 Add krb5-libs to AMD64 Alpine 3.15 image
  src/alpine/3.15/helix/amd64/Dockerfile
Labels: area-dockerfiles

#821 Rename 3130 images to net8 and add floating tags
  src/ubuntu/18.04/webassembly-net8/Dockerfile
  src/ubuntu/20.04/webassembly-net8/Dockerfile
  src/ubuntu/manifest.json
  src/windowsservercore/ltsc2022/helix/webassembly-net8/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly-net8/arial.ttf
  src/windowsservercore/manifest.json
Labels: area-dockerfiles

#828 update MsQuic on Debian ARM32 and OpenSUSE
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/opensuse/15.2/helix/amd64/Dockerfile
Labels: area-documentation, untriaged

#827 add MsQuic 2.1.8 to Ubuntu 18 ARM images
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
Labels: area-dockerfiles, untriaged

#829 Add signing keys for raspbian and debian sid rootfs build
  src/raspbian/10/crossdeps/Dockerfile
  src/ubuntu/22.04/crossdeps/Dockerfile
Labels: area-infrastructure, untriaged

#835 Add 'su' to mariner images
  src/cbl-mariner/2.0/crossdeps/Dockerfile
Labels: area-dockerfiles, untriaged
