Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-01, with the labels that each got.

#753 Set jsvu bin path
  src/ubuntu/20.04/helix/wasm/amd64/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly/Dockerfile
Labels: area-dockerfiles

#756 Update the node and npm so that newer jsvu and v8 work
  src/ubuntu/20.04/helix/wasm/amd64/Dockerfile
  src/windowsservercore/ltsc2019/webassembly/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly/Dockerfile
Labels: area-infrastructure

#759 Add retry operations to install cross-build pre-reqs script
  src/ubuntu/build-scripts/install-cross-build-prereqs.sh
Labels: area-infrastructure

#760 Set an actual wait value for retry
  src/ubuntu/build-scripts/install-cross-build-prereqs.sh
Labels: area-infrastructure

#762 [Rollout] Production rollout - 2023-1-11
  eng/common/templates/variables/docker-images.yml
  src/ubuntu/18.04/cross/x86-linux/hooks/pre-build
  src/ubuntu/18.04/webassembly/Dockerfile
  src/ubuntu/20.04/helix/wasm/amd64/Dockerfile
  src/ubuntu/build-scripts/install-cross-build-prereqs.sh
  src/windowsservercore/ltsc2019/webassembly/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly/Dockerfile
  src/windowsservercore/manifest.json
Labels: area-infrastructure

#763 Include link to production version of image info file
  README.md
Labels: area-documentation

#764 Increase retry count for waiting to install cross build packages
  src/ubuntu/build-scripts/install-cross-build-prereqs.sh
Labels: area-infrastructure

#766 Use alpine 3.14 in alpine-arm rootfs
  src/ubuntu/18.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/arm-alpine/hooks/pre-build
Labels: area-dockerfiles

#769 Add OpenSSL 1.1 to Fedora 36 to support VMR Codespaces
  src/fedora/36/amd64/Dockerfile
Labels: area-dockerfiles

#754 Add arm64 cross-build images targeting Ubuntu 16.04
  README.md
  src/ubuntu/20.04/cross/arm64/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles

#770 [Rollout] Production rollout - 2023-01-18
  README.md
  eng/common/Install-DotNetSdk.ps1
  eng/common/templates/jobs/build-images.yml
  eng/common/templates/variables/docker-images.yml
  src/fedora/36/amd64/Dockerfile
  src/ubuntu/18.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/20.04/cross/arm64/Dockerfile
  src/ubuntu/22.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/build-scripts/install-cross-build-prereqs.sh
  src/ubuntu/manifest.json
Labels: area-infrastructure

#774 Install latest v8 on ubuntu 18.04
  src/ubuntu/18.04/helix/webassembly/Dockerfile
Labels: area-infrastructure

#775 [u1804/helix/wasm] Add chromedriver dependencies
  src/ubuntu/18.04/helix/webassembly/Dockerfile
Labels: area-dockerfiles

#752 Update testrunner Dockerfile to Debian Bullseye
  src/debian/10/docker-testrunner/amd64/Dockerfile
  src/debian/10/docker-testrunner/arm64v8/Dockerfile
  src/debian/11/docker-testrunner/Dockerfile
  src/debian/manifest.json
Labels: area-infrastructure

#782 Fix workaround for helixbot user privileges
  src/debian/12/helix/arm64v8/Dockerfile
Labels: area-dockerfiles

#781 Fix rootfs dir
  src/ubuntu/20.04/cross/arm64/Dockerfile
Labels: area-samples

#783 [wasi] Image with emscripten 3.1.30
  src/ubuntu/20.04/webassembly-3130/Dockerfile
  src/ubuntu/manifest.json
Labels: area-infrastructure

#784 Disable image caching for production branch builds
  eng/pipelines/variables/common.yml
Labels: area-infrastructure
