Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-02, with the labels that each got.

#785 [Rollout] Production deployment, 2023-02-01
  eng/pipelines/variables/common.yml
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/debian/manifest.json
  src/ubuntu/18.04/webassembly-3130/Dockerfile
  src/ubuntu/20.04/cross/arm64/Dockerfile
  src/ubuntu/20.04/webassembly-3130/Dockerfile
  src/ubuntu/manifest.json
  src/windowsservercore/ltsc2022/helix/webassembly-3130/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly-3130/arial.ttf
  src/windowsservercore/manifest.json
Labels: area-documentation

#779 Add Helix image for Mariner 2.0
  src/cbl-mariner/2.0/amd64/Dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles

#787 Add FreeBSD 13 x64 image
  src/ubuntu/18.04/cross/freebsd/13/Dockerfile
  src/ubuntu/18.04/cross/freebsd/13/hooks/post-build
  src/ubuntu/18.04/cross/freebsd/13/hooks/pre-build
  src/ubuntu/manifest.json
Labels: area-dockerfiles

#789 Remove base image override for Alpine
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
  eng/pipelines/dotnet-buildtools-prereqs-alpine.yml
Labels: area-dockerfiles

#792 fix locale setting for Alpine 3.17
  src/alpine/3.17/helix/amd64/Dockerfile
Labels: area-dockerfiles

#793 fix helix Ubuntu 22 build on arm64
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-infrastructure

#795 Fix logic to detect PR build for production branch
  eng/pipelines/variables/common.yml
Labels: area-infrastructure

#797 Add alpine 3.17 (non-helix) dockerfile
  src/alpine/3.17/amd64/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles

#799 improve Alpine 3.17 helix image
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles

#798 fix locale setting for Alpine 3.16
  src/alpine/3.16/helix/amd64/Dockerfile
Labels: area-dockerfiles

#801 add icu-data-full to Helix alpine images
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
Labels: area-dockerfiles

#800 add msquic to Centos7
  src/centos/7/mlnet/helix/Dockerfile
Labels: area-dockerfiles

#803 [Rollout] Production rollout, 2022-02-15
  eng/pipelines/variables/common.yml
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.17/amd64/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/manifest.json
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-release

#806 refactor Alpine Helix image
  src/alpine/3.17/helix/amd64/Dockerfile
Labels: area-dockerfiles

#814 Set main to push non-staging tags
  eng/pipelines/variables/common.yml
Labels: area-samples

#816 add krb5-libs to Alpine 3.17 image
  src/alpine/3.17/helix/amd64/Dockerfile
Labels: area-dockerfiles
