Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-04, with the labels that each got.

#836 Add arm mariner build images
  src/cbl-mariner/2.0/cross/arm-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/arm/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-infrastructure, untriaged

#841 Install diffutils in mariner images
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/2.0/crossdeps/Dockerfile
Labels: area-dockerfiles, untriaged

#840 Upgrade mariner images to LLVM 16
  src/cbl-mariner/2.0/cross/amd64-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/arm-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/arm/Dockerfile
  src/cbl-mariner/2.0/cross/arm64-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/x86/Dockerfile
  src/cbl-mariner/2.0/crossdeps-amd64/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/2.0/crossdeps-llvm/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles, untriaged

#842 Build llvm using clang on mariner
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
Labels: area-infrastructure, untriaged

#844 Add Azure DevOps dependencies to mariner fpm image
  src/cbl-mariner/2.0/fpm/amd64/Dockerfile
Labels: untriaged

#843 Add runtime build dependencies to ubuntu 22.04 image
  src/ubuntu/22.04/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#853 Include sanitizer runtimes from LLVM in our cross-builds.
  src/cbl-mariner/2.0/cross/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/arm/Dockerfile
  src/cbl-mariner/2.0/cross/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/x86/Dockerfile
Labels: area-dockerfiles

#858 [wasm] Checkout the version tag
  src/ubuntu/18.04/webassembly/Dockerfile
  src/ubuntu/20.04/webassembly/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly-net8/Dockerfile
Labels: area-dockerfiles, untriaged

#861 [wasm] Checkout the version tag
  src/ubuntu/18.04/webassembly-net8/Dockerfile
  src/ubuntu/20.04/webassembly-net8/Dockerfile
Labels: area-dockerfiles, untriaged
