Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-12, with the labels that each got.

#936 use icu-data-full for runtime tests to pass
  src/alpine/3.16/helix/arm32v7/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#937 Update NodeJS on Windows for Wasm tests
  src/windowsservercore/ltsc2022/helix/webassembly/Dockerfile
Labels: area-infrastructure, untriaged

#939 Add msquic to debian12
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
Labels: untriaged

#941 Install icu for Fedora 39
  src/fedora/39/amd64/Dockerfile
Labels: untriaged

#940 Added in docker image for ML.Net for centos-stream8
  src/centos/manifest.json
  src/centos/stream8/mlnet/Dockerfile
Labels: area-dockerfiles, untriaged
