Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-11, with the labels that each got.

#930 Switch centos from stream9-development to stream9
  src/centos/stream9/Dockerfile
  src/centos/stream9/helix/amd64/Dockerfile
Labels: area-documentation, untriaged

#932 Add LLVM to helix workloads to enable build machine symbolization scenarios
  src/alpine/3.15/helix/amd64/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#931 fix msquic build on Alpine 3.16
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm32v7/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#934 Add Fedora 39
  src/fedora/39/amd64/Dockerfile
  src/fedora/39/amd64/microsoft.asc
  src/fedora/manifest.json
Labels: area-dockerfiles, untriaged
