Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-05, with the labels that each got.

#862 Add sudo to the FPM CBL-Mariner image
  src/cbl-mariner/2.0/fpm/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#868 Add an AlmaLinux-based image for us to use for our source-build legs
  src/almalinux/8/source-build/amd64/Dockerfile
  src/almalinux/manifest.json
Labels: area-infrastructure, untriaged

#859 Add gcc 13 image
  src/debian/12/gcc13/Dockerfile
  src/debian/manifest.json
Labels: area-dockerfiles, untriaged

#857 Add images for cross-compiling against Ubuntu 18.04, not 16.04
  src/cbl-mariner/2.0/cross/bionic/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/x86/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-infrastructure, untriaged

#874 Add a Mariner-based Android build image
  src/cbl-mariner/2.0/android/Dockerfile
  src/cbl-mariner/2.0/android/docker/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles

#875 Add additional test deps to CentOS Stream 8 dockerfile
  src/centos/stream8/Dockerfile
Labels: area-infrastructure, untriaged

#873 Create a Mariner-based image for builds targetting WASM
  src/cbl-mariner/2.0/webassembly/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles

#877 Install zip package in the Android image
  src/cbl-mariner/2.0/android/Dockerfile
Labels: area-dockerfiles

#878 Add su to the new android and webassembly images.
  src/cbl-mariner/2.0/android/Dockerfile
  src/cbl-mariner/2.0/webassembly/Dockerfile
Labels: area-dockerfiles

#876 Add awk for ICU build
  src/cbl-mariner/2.0/android/Dockerfile
Labels: area-infrastructure, untriaged

#880 Add openssl headers to the Android image for linux-bionic builds
  src/cbl-mariner/2.0/android/Dockerfile
Labels: area-dockerfiles, untriaged
