Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2023-06, with the labels that each got.

#881 Make the wasm dockerfile depend on the amd64 cross build docker image
  src/cbl-mariner/2.0/webassembly/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles, untriaged

#884 add missing libnuma.so to Stream8
  src/centos/stream8/helix/amd64/Dockerfile
Labels: area-documentation, untriaged

#885 Update ubuntu18.04 arm msquic packages to 2.2.0
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#886 Update Fedora 36 to Fedora 38
  src/fedora/38/amd64/Dockerfile
  src/fedora/38/amd64/microsoft.asc
  src/fedora/38/helix/amd64/Dockerfile
  src/fedora/manifest.json
Labels: area-documentation, untriaged

#887 Remove Fedora from base image override
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
Labels: area-infrastructure, untriaged

#879 Delete gcc12 image
  src/debian/11/gcc12/Dockerfile
  src/debian/manifest.json
Labels: area-dockerfiles, untriaged

#888 Add image for Ubuntu20.04 with sqlserver/helix
  src/ubuntu/20.04/helix/sqlserver/amd64/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#889 Update V8 version to match the version we are using in testing (and that matches the devcontainer in dotnet/runtime)
  src/cbl-mariner/2.0/webassembly/Dockerfile
Labels: area-dockerfiles

#891 Add the VMR's additional test deps to more dockerfiles
  src/alpine/3.17/amd64/Dockerfile
  src/centos/stream9/Dockerfile
  src/debian/11/amd64/Dockerfile
  src/fedora/38/amd64/Dockerfile
  src/ubuntu/20.04/amd64/Dockerfile
  src/ubuntu/22.04/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#892 Remove base image override logic for Fedora
  eng/pipelines/dotnet-buildtools-prereqs-fedora.yml
Labels: area-infrastructure, untriaged

#894 fix build break with apt-get
  src/debian/10/helix/amd64/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#895 Revert "add missing libnuma.so to Stream8"
  src/centos/stream8/helix/amd64/Dockerfile
Labels: area-documentation, untriaged

#896 Copy the sanitizer runtimes into /usr/local
  src/cbl-mariner/2.0/cross/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/arm/Dockerfile
  src/cbl-mariner/2.0/cross/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/x86/Dockerfile
  src/cbl-mariner/2.0/cross/x86/Dockerfile
Labels: area-dockerfiles, untriaged

#898 Add libatomic to Centos Stream 8 image
  src/centos/stream8/Dockerfile
Labels: area-dockerfiles, untriaged

#899 add ubuntu-20.04-arm64 image
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged
