Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-06, with the labels that each got.

#1086 Delete CentOS Stream 8 Dockerfiles
  src/centos/manifest.json
  src/centos/stream8/amd64/Dockerfile
  src/centos/stream8/helix/amd64/Dockerfile
  src/centos/stream8/mlnet/amd64/Dockerfile
  src/centos/stream8/mlnet/helix/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1089 Do not install emscripten anymore
  src/windowsservercore/ltsc2022/helix/webassembly/amd64/Dockerfile
Labels: untriaged, area-samples

#1091 Add Alpine 3.20 Helix images
  src/alpine/3.20/helix/amd64/Dockerfile
  src/alpine/3.20/helix/arm32v7/Dockerfile
  src/alpine/3.20/helix/arm64v8/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#1094 Transition from virtualenv to venv
  src/debian/12/helix/amd64/Dockerfile
Labels: area-documentation, untriaged

#1098 Move riscv64 to Azure Linux
  src/azurelinux/3.0/net9.0/cross/riscv64-alpine/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/manifest.json
  src/ubuntu/22.04/cross/riscv64-alpine/Dockerfile
  src/ubuntu/22.04/cross/riscv64/Dockerfile
  src/ubuntu/manifest.json
Labels: untriaged

#1095 Switch from virtualenv to venv for all helix Dockerfiles
  src/almalinux/8/helix/amd64/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
  src/centos/stream9/helix/amd64/Dockerfile
  src/debian/11/helix/amd64/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/opensuse/15.4/helix/amd64/Dockerfile
  src/ubuntu/20.04/helix/amd64/Dockerfile
  src/ubuntu/22.04/helix/amd64/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
Labels: area-dockerfiles, untriaged

#1105 Fix Arm emulation for Ubuntu 22.04
  src/ubuntu/22.04/cross/arm/Dockerfile
Labels: area-infrastructure, untriaged

#1104 Pin debootstrap to tag 1.0.134 and fix azurelinux 3.0 build
  src/azurelinux/3.0/net8.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net8.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/webassembly/amd64/Dockerfile
Labels: area-dockerfiles

#1080 Refactor ARG pattern used in cross images
  src/azurelinux/3.0/net8.0/cross/amd64-alpine/Dockerfile
  src/azurelinux/3.0/net8.0/cross/amd64/Dockerfile
  src/azurelinux/3.0/net8.0/cross/arm-alpine/Dockerfile
  src/azurelinux/3.0/net8.0/cross/arm/Dockerfile
  src/azurelinux/3.0/net8.0/cross/arm64-alpine/Dockerfile
  src/azurelinux/3.0/net8.0/cross/arm64/Dockerfile
  src/azurelinux/3.0/net8.0/cross/x86/Dockerfile
  src/azurelinux/3.0/net9.0/cross/amd64-alpine/Dockerfile
  src/azurelinux/3.0/net9.0/cross/amd64-sanitizer/Dockerfile
  src/azurelinux/3.0/net9.0/cross/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/arm-alpine/Dockerfile
  src/azurelinux/3.0/net9.0/cross/arm/Dockerfile
  src/azurelinux/3.0/net9.0/cross/arm64-alpine/Dockerfile
  src/azurelinux/3.0/net9.0/cross/arm64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/armv6/Dockerfile
  src/azurelinux/3.0/net9.0/cross/freebsd/13/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/ppc64le/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64-alpine/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/s390x/Dockerfile
  src/azurelinux/3.0/net9.0/cross/x86/Dockerfile
  src/cbl-mariner/2.0/cross/amd64-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/arm-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/arm/Dockerfile
  src/cbl-mariner/2.0/cross/arm64-alpine/Dockerfile
  src/cbl-mariner/2.0/cross/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/armv6/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/bionic/x86/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/13/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/13/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/14/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/14/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/ppc64le/Dockerfile
  src/cbl-mariner/2.0/cross/s390x/Dockerfile
  src/cbl-mariner/2.0/cross/x86/Dockerfile
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/ubuntu/20.04/cross/arm64/Dockerfile
  src/ubuntu/20.04/crossdeps/Dockerfile
  src/ubuntu/22.04/cross/arm-alpine/Dockerfile
  src/ubuntu/22.04/cross/arm/Dockerfile
  src/ubuntu/22.04/cross/arm64-alpine/Dockerfile
  src/ubuntu/22.04/cross/arm64/Dockerfile
  src/ubuntu/22.04/cross/armel-tizen/Dockerfile
  src/ubuntu/22.04/cross/haiku/Dockerfile
  src/ubuntu/22.04/cross/ppc64le-alpine/Dockerfile
  src/ubuntu/22.04/cross/s390x-alpine/Dockerfile
  src/ubuntu/22.04/cross/x86-alpine/Dockerfile
Labels: area-dockerfiles, untriaged

#1100 Install Powershell on Alpine 3.19
  src/alpine/3.19/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1113 Install Powershell on Alpine 3.20
  src/alpine/3.20/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1108 Install azure cli and powershell on azure linux 3.0
  src/azurelinux/3.0/net8.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps/amd64/Dockerfile
Labels: untriaged

#1114 Move illumos to Ubuntu 22.04
  src/ubuntu/22.04/cross/illumos/Dockerfile
  src/ubuntu/manifest.json
Labels: area-infrastructure, untriaged

#1096 Add missing Ubuntu 20.04 and 24.04 helix images
  src/ubuntu/20.04/helix/Dockerfile
  src/ubuntu/22.04/helix/Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1112 Install powershell and azure-cli on cbl mar 2.0 crossdeps
  src/cbl-mariner/2.0/crossdeps/amd64/Dockerfile
Labels: untriaged

#1111 Install powershell and azure-cli on cbl mar 2.0
  src/cbl-mariner/2.0/fpm/amd64/Dockerfile
Labels: untriaged

#1109 Install azure cli via script and update depkg image derive from core
  src/ubuntu/22.04/coredeps/Dockerfile
  src/ubuntu/22.04/debpkg/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1117 Fix up debpkg image
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/debpkg/amd64/Dockerfile
Labels: area-dockerfiles, untriaged
