Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-12, with the labels that each got.

#1280 Add a Fedora 41 helix image
  src/fedora/41/helix/Dockerfile
  src/fedora/manifest.json
Labels: area-dockerfiles, untriaged

#1277 Add 24.10 helix images
  src/ubuntu/24.10/helix/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1274 Add lifecycle document
  README.md
  lifecycle.md
Labels: area-documentation, untriaged

#1282 Add Alpine 3.21 helix images
  src/alpine/3.21/helix/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#1272 Delete EOL'd freebsd 13
  src/azurelinux/3.0/net10.0/cross/freebsd/14/amd64/Dockerfile
  src/azurelinux/3.0/net10.0/cross/freebsd/14/arm64/Dockerfile
  src/azurelinux/3.0/net8.0/cross/freebsd/14/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/freebsd/14/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/freebsd/14/arm64/Dockerfile
  src/azurelinux/manifest.json
  src/cbl-mariner/2.0/cross/freebsd/13/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/13/arm64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/14/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/14/arm64/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles, untriaged

#1289 Delete libgdiplus from all images
  src/debian/11/amd64/Dockerfile
  src/debian/11/helix/amd64/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/11/opt/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/fedora/40/amd64/Dockerfile
  src/fedora/41/amd64/Dockerfile
  src/opensuse/15.6/helix/amd64/Dockerfile
  src/ubuntu/20.04/Dockerfile
  src/ubuntu/20.04/helix/Dockerfile
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/helix/Dockerfile
  src/ubuntu/24.04/Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
  src/ubuntu/24.10/helix/Dockerfile
  src/ubuntu/common/coredeps/Dockerfile
Labels: area-dockerfiles, untriaged

#1290 bump wasmtime to 27.0.0
  src/azurelinux/3.0/net10.0/webassembly/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1291 Remove vulnerable packages in net8.0 webassembly image
  src/azurelinux/3.0/net8.0/webassembly/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1284 Add Alpine 3.21 Dockerfile
  src/alpine/3.21/amd64/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#1294 Update readme on when images get built
  README.md
Labels: area-documentation, untriaged

#1288 Add Debian trixie image
  src/debian/13/helix/Dockerfile
  src/debian/manifest.json
Labels: untriaged

#1293 Update Ubuntu 24.10 libmsquic version
  src/ubuntu/24.10/helix/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles

#1296 Add Node to Alpine 3.21
  src/alpine/3.21/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1297 Update npm ip package to address CVE
  src/ubuntu/20.04/Dockerfile
  src/ubuntu/22.04/Dockerfile
Labels: area-dockerfiles, untriaged

#1298 Add CentOS Stream 10 test image
  CODEOWNERS
  manifest.json
  src/centos-stream/10.0/helix/Dockerfile
  src/centos-stream/9.0/amd64/Dockerfile
  src/centos-stream/9.0/helix/amd64/Dockerfile
  src/centos-stream/9.0/mlnet/helix/Dockerfile
  src/centos-stream/manifest.json
  src/centos/manifest.json
Labels: area-infrastructure, untriaged

#1301 Azure Linux cross riscv464: Update debootstrap to 1.0.138
  src/azurelinux/3.0/net10.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net8.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
Labels: area-infrastructure, untriaged

#1305 Install pip on Alpine >= 3.19
  src/alpine/3.19/amd64/Dockerfile
  src/alpine/3.20/amd64/Dockerfile
  src/alpine/3.21/amd64/Dockerfile
Labels: untriaged, area-release
