Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-05, with the labels that each got.

#1030 Split the crossdeps base image to allow CI to generate separate jobs for the net8.0 and net9.0 images
  src/azurelinux/3.0/crossdeps-llvm-net8.0/Dockerfile
  src/azurelinux/3.0/crossdeps-llvm-net9.0/Dockerfile
  src/azurelinux/3.0/crossdeps-net8.0/Dockerfile
  src/azurelinux/3.0/crossdeps-net9.0/Dockerfile
  src/azurelinux/manifest.json
Labels: area-dockerfiles, untriaged

#1038 Revert "Update our AZLinux 3.0 .NET 9 images to build a custom standard library toolchain"
  src/azurelinux/3.0/cross/amd64-alpine-net9.0/Dockerfile
  src/azurelinux/3.0/cross/amd64-net9.0-asan/Dockerfile
  src/azurelinux/3.0/cross/amd64-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm-alpine-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm64-alpine-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm64-net9.0/Dockerfile
  src/azurelinux/3.0/cross/x86-net9.0/Dockerfile
  src/azurelinux/manifest.json
Labels: area-infrastructure, untriaged

#1048 Fix architecture of new Debian images
  src/debian/manifest.json
Labels: area-infrastructure, untriaged

#1042 Upgrade gcc to v14
  src/debian/12/gcc14/Dockerfile
  src/debian/manifest.json
Labels: area-infrastructure, untriaged

#1047 Move all Dockerfiles to arch-specific dir
  src/azurelinux/3.0/crossdeps-builder-net8.0/amd64/Dockerfile
  src/azurelinux/3.0/crossdeps-builder-net8.0/amd64/dimitri_john_ledkov.asc
  src/azurelinux/3.0/crossdeps-builder-net9.0/amd64/Dockerfile
  src/azurelinux/3.0/crossdeps-builder-net9.0/amd64/dimitri_john_ledkov.asc
  src/azurelinux/3.0/crossdeps-llvm-net8.0/amd64/Dockerfile
  src/azurelinux/3.0/crossdeps-llvm-net9.0/amd64/Dockerfile
  src/azurelinux/3.0/crossdeps-net8.0/amd64/Dockerfile
  src/azurelinux/3.0/crossdeps-net9.0/amd64/Dockerfile
  src/azurelinux/manifest.json
  src/cbl-mariner/2.0/crossdeps-builder/amd64/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/amd64/dimitri_john_ledkov.asc
  src/cbl-mariner/2.0/crossdeps-llvm/amd64/Dockerfile
  src/cbl-mariner/2.0/crossdeps/amd64/Dockerfile
  src/cbl-mariner/2.0/webassembly/amd64/Dockerfile
  src/cbl-mariner/manifest.json
  src/centos/7/amd64/Dockerfile
  src/centos/7/mlnet/amd64/Dockerfile
  src/centos/7/mlnet/helix/amd64/Dockerfile
  src/centos/manifest.json
  src/centos/stream8/amd64/Dockerfile
  src/centos/stream8/mlnet/amd64/Dockerfile
  src/centos/stream8/mlnet/helix/amd64/Dockerfile
  src/centos/stream9/amd64/Dockerfile
  src/debian/12/gcc14/amd64/Dockerfile
  src/debian/manifest.json
  src/raspbian/10/crossdeps/arm32v7/Dockerfile
  src/raspbian/manifest.json
  src/ubuntu/18.04/crossdeps/amd64/Dockerfile
  src/ubuntu/18.04/debpkg/amd64/Dockerfile
  src/ubuntu/18.04/helix/webassembly/amd64/Dockerfile
  src/ubuntu/18.04/mlnet/amd64/Dockerfile
  src/ubuntu/18.04/mlnet/helix/amd64/Dockerfile
  src/ubuntu/18.04/webassembly-net8/amd64/Dockerfile
  src/ubuntu/18.04/webassembly/amd64/Dockerfile
  src/ubuntu/20.04/webassembly-net8/amd64/Dockerfile
  src/ubuntu/20.04/webassembly/amd64/Dockerfile
  src/ubuntu/22.04/debpkg/amd64/Dockerfile
  src/ubuntu/22.04/helix/webassembly/amd64/Dockerfile
  src/ubuntu/22.04/helix/webassembly/amd64/setup-node-18.x.sh
  src/ubuntu/manifest.json
  src/windowsservercore/ltsc2019/webassembly/amd64/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly-net8/amd64/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly-net8/amd64/arial.ttf
  src/windowsservercore/ltsc2022/helix/webassembly/amd64/Dockerfile
  src/windowsservercore/ltsc2022/helix/webassembly/amd64/arial.ttf
  src/windowsservercore/manifest.json
Labels: area-infrastructure, untriaged

#1020 Switch from dotnet/msquic to microsoft/msquic
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#1045 Use Ubuntu registry instead of Docker Hub
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
  eng/pipelines/dotnet-buildtools-prereqs-ubuntu.yml
  src/raspbian/10/crossdeps/arm32v7/Dockerfile
  src/ubuntu/18.04/amd64/Dockerfile
  src/ubuntu/18.04/arm32v7/Dockerfile
  src/ubuntu/18.04/arm64v8/Dockerfile
  src/ubuntu/18.04/helix/amd64/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/18.04/mono/amd64/Dockerfile
  src/ubuntu/18.04/mono/arm32v7/Dockerfile
  src/ubuntu/18.04/mono/arm64v8/Dockerfile
  src/ubuntu/20.04/amd64/Dockerfile
  src/ubuntu/20.04/helix/amd64/Dockerfile
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/helix/amd64/Dockerfile
  src/ubuntu/22.04/helix/arm64v8/Dockerfile
  src/ubuntu/22.04/opt/arm64v8/Dockerfile
Labels: area-documentation, untriaged

#1050 Remove support for Ubuntu 18.04
  src/ubuntu/18.04/amd64/Dockerfile
  src/ubuntu/18.04/android/Dockerfile
  src/ubuntu/18.04/arm32v7/Dockerfile
  src/ubuntu/18.04/arm64v8/Dockerfile
  src/ubuntu/18.04/coredeps/Dockerfile
  src/ubuntu/18.04/cross/Dockerfile
  src/ubuntu/18.04/cross/arm-alpine/Dockerfile
  src/ubuntu/18.04/cross/arm-alpine/hooks/post-build
  src/ubuntu/18.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/18.04/cross/arm/Dockerfile
  src/ubuntu/18.04/cross/arm/hooks/post-build
  src/ubuntu/18.04/cross/arm/hooks/pre-build
  src/ubuntu/18.04/cross/arm64-alpine/Dockerfile
  src/ubuntu/18.04/cross/arm64-alpine/hooks/post-build
  src/ubuntu/18.04/cross/arm64-alpine/hooks/pre-build
  src/ubuntu/18.04/cross/arm64/Dockerfile
  src/ubuntu/18.04/cross/arm64/hooks/post-build
  src/ubuntu/18.04/cross/arm64/hooks/pre-build
  src/ubuntu/18.04/cross/armel-tizen/Dockerfile
  src/ubuntu/18.04/cross/armel-tizen/hooks/post-build
  src/ubuntu/18.04/cross/armel-tizen/hooks/pre-build
  src/ubuntu/18.04/cross/hooks/post-build
  src/ubuntu/18.04/cross/hooks/pre-build
  src/ubuntu/18.04/cross/illumos/Dockerfile
  src/ubuntu/18.04/cross/illumos/hooks/post-build
  src/ubuntu/18.04/cross/illumos/hooks/pre-build
  src/ubuntu/18.04/cross/ppc64le/Dockerfile
  src/ubuntu/18.04/cross/ppc64le/hooks/post-build
  src/ubuntu/18.04/cross/ppc64le/hooks/pre-build
  src/ubuntu/18.04/cross/s390x/Dockerfile
  src/ubuntu/18.04/cross/s390x/hooks/post-build
  src/ubuntu/18.04/cross/s390x/hooks/pre-build
  src/ubuntu/18.04/cross/x86-linux/Dockerfile
  src/ubuntu/18.04/cross/x86-linux/hooks/post-build
  src/ubuntu/18.04/cross/x86-linux/hooks/pre-build
  src/ubuntu/18.04/crossdeps/amd64/Dockerfile
  src/ubuntu/18.04/debpkg/amd64/Dockerfile
  src/ubuntu/18.04/helix/amd64/Dockerfile
  src/ubuntu/18.04/helix/arm32v7/Dockerfile
  src/ubuntu/18.04/helix/arm64v8/Dockerfile
  src/ubuntu/18.04/helix/sqlserver/amd64/Dockerfile
  src/ubuntu/18.04/helix/webassembly/amd64/Dockerfile
  src/ubuntu/18.04/mlnet/amd64/Dockerfile
  src/ubuntu/18.04/mlnet/cross/arm/Dockerfile
  src/ubuntu/18.04/mlnet/cross/arm/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm/hooks/pre-build
  src/ubuntu/18.04/mlnet/cross/arm64/Dockerfile
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/post-build
  src/ubuntu/18.04/mlnet/cross/arm64/hooks/pre-build
  src/ubuntu/18.04/mlnet/helix/amd64/Dockerfile
  src/ubuntu/18.04/mono/amd64/Dockerfile
  src/ubuntu/18.04/mono/arm32v7/Dockerfile
  src/ubuntu/18.04/mono/arm64v8/Dockerfile
  src/ubuntu/18.04/webassembly-net8/amd64/Dockerfile
  src/ubuntu/18.04/webassembly/amd64/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1051 Remove support for Fedora 38
  src/fedora/38/amd64/Dockerfile
  src/fedora/38/amd64/microsoft.asc
  src/fedora/38/helix/amd64/Dockerfile
  src/fedora/manifest.json
Labels: untriaged

#1052 Add Fedora 40 Support
  src/fedora/40/amd64/Dockerfile
  src/fedora/40/amd64/microsoft.asc
  src/fedora/manifest.json
Labels: untriaged

#1054 Use SBOM Manifest Generator Task from 1ES PT
  eng/common/templates/jobs/build-images.yml
Labels: area-infrastructure, untriaged

#1056 Add Ubuntu 20.04 arm64 support
  src/ubuntu/20.04/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1058 Add support for Ubuntu 24.04
  src/ubuntu/24.04/Dockerfile
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1057 Add azure-cli to docker-testrunner
  src/cbl-mariner/2.0/docker-testrunner/Dockerfile
  src/cbl-mariner/2.0/fpm/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1060 Remove support for EOL openSUSE 15.2 and add support for openSUSE 15.4
  src/opensuse/15.4/helix/amd64/Dockerfile
  src/opensuse/manifest.json
Labels: area-infrastructure, untriaged

#1063 Use XL pools for Mariner/Azure Linux
  eng/pipelines/dotnet-buildtools-prereqs-all-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
  eng/pipelines/dotnet-buildtools-prereqs-azurelinux-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-azurelinux.yml
  eng/pipelines/dotnet-buildtools-prereqs-mariner-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-mariner.yml
  eng/pipelines/stages/build-test-publish-repo.yml
Labels: area-infrastructure, untriaged

#1064 Build msquic in a separate docker stage
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
Labels: area-dockerfiles, untriaged

#1065 Remove hooks from all images
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/raspbian/10/helix/arm32v6/hooks/post-build
  src/raspbian/10/helix/arm32v6/hooks/pre-build
  src/ubuntu/22.04/cross/arm-alpine/Dockerfile
  src/ubuntu/22.04/cross/arm-alpine/hooks/post-build
  src/ubuntu/22.04/cross/arm-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/arm/Dockerfile
  src/ubuntu/22.04/cross/arm/hooks/post-build
  src/ubuntu/22.04/cross/arm/hooks/pre-build
  src/ubuntu/22.04/cross/arm64-alpine/Dockerfile
  src/ubuntu/22.04/cross/arm64-alpine/hooks/post-build
  src/ubuntu/22.04/cross/arm64-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/arm64/Dockerfile
  src/ubuntu/22.04/cross/arm64/hooks/post-build
  src/ubuntu/22.04/cross/arm64/hooks/pre-build
  src/ubuntu/22.04/cross/haiku/Dockerfile
  src/ubuntu/22.04/cross/haiku/hooks/post-build
  src/ubuntu/22.04/cross/haiku/hooks/pre-build
  src/ubuntu/22.04/cross/ppc64le-alpine/Dockerfile
  src/ubuntu/22.04/cross/ppc64le-alpine/hooks/post-build
  src/ubuntu/22.04/cross/ppc64le-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/riscv64-alpine/Dockerfile
  src/ubuntu/22.04/cross/riscv64-alpine/hooks/post-build
  src/ubuntu/22.04/cross/riscv64-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/riscv64/Dockerfile
  src/ubuntu/22.04/cross/riscv64/hooks/post-build
  src/ubuntu/22.04/cross/riscv64/hooks/pre-build
  src/ubuntu/22.04/cross/s390x-alpine/Dockerfile
  src/ubuntu/22.04/cross/s390x-alpine/hooks/post-build
  src/ubuntu/22.04/cross/s390x-alpine/hooks/pre-build
  src/ubuntu/22.04/cross/x86-alpine/Dockerfile
  src/ubuntu/22.04/cross/x86-alpine/hooks/post-build
  src/ubuntu/22.04/cross/x86-alpine/hooks/pre-build
  src/ubuntu/build-scripts/build-rootfs-cleanup.sh
  src/ubuntu/build-scripts/run-arcade-build-rootfs.sh
Labels: area-dockerfiles, untriaged

#1068 Revert "Build msquic in a separate docker stage"
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#1070 Try 2: Split MSQuic building into a separate stage
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
Labels: area-infrastructure, untriaged

#1071 Install azure powershell and az cli on centos stream 8
  src/centos/stream8/amd64/Dockerfile
  src/centos/stream9/amd64/Dockerfile
Labels: untriaged, area-samples

#1069 Pin Azure Linux 3.0 base to a working version
  src/azurelinux/3.0/net8.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net8.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1075 Quote path for exclusion
  eng/pipelines/dotnet-buildtools-prereqs-eng.yml
Labels: area-infrastructure, untriaged

#1062 Create AzureLinux 3.0 images for the remaining images used in the dotnet/runtime build
  src/azurelinux/3.0/net9.0/android/Dockerfile
  src/azurelinux/3.0/net9.0/android/docker/Dockerfile
  src/azurelinux/3.0/net9.0/cross/android/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/freebsd/13/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/ppc64le/Dockerfile
  src/azurelinux/3.0/net9.0/cross/s390x/Dockerfile
  src/azurelinux/3.0/net9.0/fpm/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/webassembly/amd64/Dockerfile
  src/azurelinux/manifest.json
Labels: area-infrastructure, untriaged

#1076 Remove symcrypt-openssl in the android-docker image
  src/azurelinux/3.0/net9.0/android/docker/Dockerfile
Labels: area-dockerfiles, untriaged

#1078 Remove eol Alpine 3.16 Dockerfiles
  src/alpine/3.16/helix/amd64/Dockerfile
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#1081 Add an image with the x64 openssl inserted into the NDK enough that CMake can find it
  src/azurelinux/3.0/net9.0/cross/android/openssl/amd64/Dockerfile
  src/azurelinux/manifest.json
Labels: area-infrastructure, untriaged

#1082 Fix armv6 image rootfs
  src/azurelinux/3.0/net9.0/cross/armv6/Dockerfile
  src/azurelinux/manifest.json
Labels: area-infrastructure, untriaged
