Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-10, with the labels that each got.

#1205 Change install repo from testing to community on Alpine for msquic
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.20/helix/Dockerfile
Labels: area-infrastructure, untriaged

#1206 Delete obsolete files in eng/common
  eng/common/templates/jobs/cg-detection.yml
  eng/common/templates/jobs/wait-for-ingestion.yml
  eng/common/templates/steps/copy-base-images-staging.yml
  eng/common/templates/steps/parse-os-versions.yml
  eng/common/templates/variables/codeql.yml
Labels: area-infrastructure, untriaged

#1207 Update llvm patch version
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1211 Add missing tsa config file
  .config/tsaconfig.json
Labels: area-dockerfiles, untriaged

#1215 Rename tsaconfig.json to tsaoptions.json
  .config/tsaoptions.json
Labels: area-infrastructure, untriaged

#1219 Optimize the Fedora 41 image
  src/fedora/41/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1223 Update checksum of llvm release keys
  src/azurelinux/3.0/net8.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/amd64/Dockerfile
Labels: untriaged, area-release

#1226 Add dnf upgrade to Fedora images
  src/fedora/39/amd64/Dockerfile
  src/fedora/40/amd64/Dockerfile
  src/fedora/41/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1231 Update almalinux images to include package upgrade logic
  src/almalinux/8/helix/amd64/Dockerfile
  src/almalinux/8/source-build/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1227 Update opensuse to 15.6
  src/opensuse/15.4/helix/amd64/Dockerfile
  src/opensuse/15.6/helix/amd64/Dockerfile
  src/opensuse/manifest.json
Labels: area-dockerfiles, untriaged
