Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-08, with the labels that each got.

#1154 Fix msquic to 2.3.6 version
  src/almalinux/8/helix/amd64/Dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
  src/centos/stream9/helix/amd64/Dockerfile
  src/debian/11/helix/amd64/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/opensuse/15.4/helix/amd64/Dockerfile
  src/ubuntu/20.04/helix/Dockerfile
  src/ubuntu/22.04/helix/Dockerfile
Labels: untriaged

#1156 Update msquic version and configure distros to use latest package again
  src/almalinux/8/helix/amd64/Dockerfile
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.20/helix/Dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
  src/centos/stream9/helix/amd64/Dockerfile
  src/debian/11/helix/amd64/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/opensuse/15.4/helix/amd64/Dockerfile
  src/ubuntu/20.04/helix/Dockerfile
  src/ubuntu/22.04/helix/Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1158 Drop Debian 11 arm64 support
  src/debian/11/arm64v8/Dockerfile
  src/debian/manifest.json
Labels: area-infrastructure, untriaged

#1153 Create CODEOWNERS and validation
  .github/workflows/codeowners-validation.yml
  CODEOWNERS
  eng/validate-codeowners.sh
Labels: area-documentation, untriaged

#1161 Add step about CODEOWNERS in README
  README.md
Labels: area-documentation, untriaged

#1162 Update gcc path in alpine-riscv64
  src/azurelinux/3.0/net9.0/cross/riscv64-alpine/Dockerfile
Labels: area-dockerfiles, untriaged

#1164 Make `@dotnet/dotnet-docker-reviewers` an owner of every file
  .github/workflows/codeowners-validation.yml
  CODEOWNERS
  README.md
  eng/validate-codeowners.sh
Labels: area-infrastructure, untriaged

#1165 Update Ubuntu 24.04 Image for msquic - Delete workarounds
  src/ubuntu/24.04/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1167 Switch to MCR images
  src/azurelinux/3.0/net8.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net8.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/fpm/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/opt/Dockerfile
Labels: area-dockerfiles, untriaged

#1166 Add helix images for Azure Linux 3.0
  src/azurelinux/3.0/helix/Dockerfile
  src/azurelinux/manifest.json
Labels: untriaged

#1170 Add libmsquic to Azure Linux images
  src/azurelinux/3.0/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1172 Update msquic version (for source-built images)
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.20/helix/Dockerfile
  src/azurelinux/3.0/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1125 Remove `zlib-devel` dependency from azurelinux for .NET 9.0
  src/azurelinux/3.0/net9.0/crossdeps/amd64/Dockerfile
Labels: area-dockerfiles, untriaged, do-not-merge

#1177 Add libnuma and libatomic
  src/azurelinux/3.0/helix/Dockerfile
Labels: area-documentation, untriaged

#1181 Remove timestamp tags for Azure Linux
  src/azurelinux/manifest.json
Labels: area-infrastructure, untriaged

#1183 Install libmsquic package
  src/azurelinux/3.0/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1185 Install azure cli and pwsh on debian 11
  src/debian/11/amd64/Dockerfile
Labels: untriaged

#1187 Install powershell and azure-cli on deb 12
  src/debian/11/amd64/Dockerfile
  src/debian/12/gcc14/amd64/Dockerfile
Labels: untriaged

#1189 Add Linter GH action
  .github/linters/.hadolint.yaml
  .github/workflows/linter.yml
Labels: area-infrastructure, untriaged

#1192 Add support for specifing multiple build paths
  README.md
  build.ps1
Labels: area-infrastructure, untriaged

#1194 Document Code Owner Responsibilities and Repo Maintainer Procedures
  README.md
Labels: area-documentation, untriaged

#1195 Use prod feed for Azure Linux 3.0
  src/azurelinux/3.0/net8.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
Labels: area-infrastructure, untriaged
