Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-02, with the labels that each got.

#968 Remove references to production branch
  README.md
  eng/pipelines/dotnet-buildtools-prereqs-all-pr.yml
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
  eng/pipelines/variables/common.yml
Labels: area-documentation, untriaged

#969 Add an Ubuntu-22.04-based Tizen build image
  src/ubuntu/22.04/cross/armel-tizen/Dockerfile
  src/ubuntu/manifest.json
Labels: area-infrastructure, untriaged

#966 Add llvm-symbolizer to all more helix images
  src/alpine/3.16/helix/arm64v8/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
  src/centos/stream8/helix/amd64/Dockerfile
  src/centos/stream9/helix/amd64/Dockerfile
  src/debian/11/helix/amd64/Dockerfile
  src/debian/11/helix/arm32v7/Dockerfile
  src/debian/11/helix/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/fedora/38/helix/amd64/Dockerfile
  src/opensuse/15.2/helix/amd64/Dockerfile
  src/ubuntu/18.04/helix/amd64/Dockerfile
  src/ubuntu/18.04/helix/webassembly/Dockerfile
  src/ubuntu/20.04/helix/amd64/Dockerfile
  src/ubuntu/22.04/helix/amd64/Dockerfile
Labels: area-dockerfiles, untriaged
