Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-07, with the labels that each got.

#1124 [wasm] Add vc redistributable for the new llvm
  src/windowsservercore/ltsc2022/helix/webassembly/amd64/Dockerfile
Labels: area-dockerfiles

#1123 Delete CentOS 7 Dockerfiles
  eng/pipelines/dotnet-buildtools-prereqs-centos.yml
  src/centos/7/amd64/Dockerfile
  src/centos/7/mlnet/amd64/Dockerfile
  src/centos/7/mlnet/helix/amd64/Dockerfile
  src/centos/7/source-build/amd64/Dockerfile
  src/centos/manifest.json
Labels: area-dockerfiles, untriaged

#1120 Add Ubuntu 24.04 Arm32 Helix Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
  src/ubuntu/manifest.json
Labels: area-infrastructure, untriaged

#1127 Use latest PowerShell version
  src/alpine/3.19/amd64/Dockerfile
  src/alpine/3.20/amd64/Dockerfile
  src/nanoserver/1809/helix/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1122 Fix remaining Helix Dockerfiles to switch to venv
  src/raspbian/10/helix/arm32v6/Dockerfile
  src/ubuntu/22.04/mlnet/helix/Dockerfile
Labels: area-infrastructure, untriaged

#1011 [WASI] update SDK 22 and wasmtime 19.0.2
  src/azurelinux/3.0/net9.0/webassembly/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1133 Add MsQuic to Ubuntu 20.04 Dockerfile
  src/ubuntu/20.04/helix/Dockerfile
Labels: area-dockerfiles

#1134 Add Node to Alma Linux SB image
  src/almalinux/8/source-build/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1135 Add SB test requirements to Alma Linux
  src/almalinux/8/source-build/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1136 Add alpine 3.20 withnode image
  src/alpine/3.20/withnode/amd64/Dockerfile
  src/alpine/manifest.json
Labels: area-infrastructure, untriaged

#1137 Add azurelinux optimization dockerfiles
  src/azurelinux/3.0/net9.0/opt/Dockerfile
  src/azurelinux/manifest.json
Labels: area-dockerfiles, untriaged

#1138 Refactor Apline Dockerfiles to use a consist and efficient apk pattern
  src/alpine/3.17/amd64/Dockerfile
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/WithNode/amd64/Dockerfile
  src/alpine/3.18/amd64/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
  src/alpine/3.19/WithNode/amd64/Dockerfile
  src/alpine/3.19/amd64/Dockerfile
  src/alpine/3.20/amd64/Dockerfile
  src/alpine/3.20/helix/amd64/Dockerfile
  src/alpine/3.20/helix/arm32v7/Dockerfile
  src/alpine/3.20/helix/arm64v8/Dockerfile
  src/alpine/3.20/withnode/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1130 add centos-streaming9-mlnet-helix docker image
  src/centos/manifest.json
  src/centos/stream9/mlnet/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1141 Update llvm.sh arguments
  src/ubuntu/22.04/crossdeps/Dockerfile
Labels: area-infrastructure, untriaged

#1144 Update debootstrap version
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
Labels: area-infrastructure, untriaged

#1145 Install newer rust version
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
Labels: area-infrastructure, untriaged

#1142 Install Helix Python packages into a venv in a separate docker stage
  src/alpine/3.17/helix/amd64/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/amd64/Dockerfile
  src/alpine/3.18/helix/arm32v7/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
  src/alpine/3.20/helix/amd64/Dockerfile
  src/alpine/3.20/helix/arm32v7/Dockerfile
  src/alpine/3.20/helix/arm64v8/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
Labels: area-dockerfiles, untriaged

#1147 Define Alpine helix images using multi-platform dockerfiles
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.17/helix/arm32v7/Dockerfile
  src/alpine/3.17/helix/arm64v8/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.18/helix/arm64v8/Dockerfile
  src/alpine/3.20/helix/Dockerfile
  src/alpine/3.20/helix/amd64/Dockerfile
  src/alpine/3.20/helix/arm32v7/Dockerfile
  src/alpine/3.20/helix/arm64v8/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#1149 Update MsQuic to main for Alpine
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.20/helix/Dockerfile
Labels: area-infrastructure, untriaged

#1152 Update debootstrap to 1.0.137
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
Labels: area-infrastructure, untriaged

#1151 Remove gpg workaround from riscv
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/crossdeps-builder/amd64/Dockerfile
  src/ubuntu/22.04/cross/illumos/Dockerfile
Labels: area-dockerfiles, untriaged
