Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-01, with the labels that each got.

#943 [ASP.NET Core] Update Centos8 Dockerfile to add support for node 20 as required for ASP.NET Core
  src/centos/stream8/Dockerfile
Labels: area-dockerfiles, untriaged

#947 Add alpine 3.19 images
  src/alpine/3.19/WithNode/amd64/Dockerfile
  src/alpine/3.19/amd64/Dockerfile
  src/alpine/manifest.json
Labels: area-dockerfiles, untriaged

#948 Set node location for Azure pipelines
  src/alpine/3.19/WithNode/amd64/Dockerfile
Labels: area-documentation, untriaged

#945 Update Debian archive keyring
  src/ubuntu/22.04/crossdeps/Dockerfile
Labels: untriaged

#944 Update Ubuntu 22.04 crossdeps to install llvm 17
  src/ubuntu/22.04/crossdeps/Dockerfile
Labels: untriaged

#953 Delete crossdac Dockerfile
  src/ubuntu/20.04/crossdac/amd64/Dockerfile
  src/ubuntu/manifest.json
Labels: area-infrastructure, untriaged

#954 Touch riscv64 Dockerfile
  src/ubuntu/22.04/cross/riscv64/Dockerfile
Labels: area-dockerfiles, untriaged

#949 Add Node to images used in SourceBuild
  src/centos/stream9/Dockerfile
  src/fedora/39/amd64/Dockerfile
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/cross/arm64/Dockerfile
Labels: area-dockerfiles, untriaged

#955 Move FreeBSD to cbl-mariner and remove v12
  src/cbl-mariner/2.0/cross/freebsd/13/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/13/arm64/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/manifest.json
  src/ubuntu/18.04/cross/freebsd-arm64/13/Dockerfile
  src/ubuntu/18.04/cross/freebsd-arm64/13/hooks/post-build
  src/ubuntu/18.04/cross/freebsd-arm64/13/hooks/pre-build
  src/ubuntu/18.04/cross/freebsd/12/Dockerfile
  src/ubuntu/18.04/cross/freebsd/12/hooks/post-build
  src/ubuntu/18.04/cross/freebsd/12/hooks/pre-build
  src/ubuntu/18.04/cross/freebsd/13/Dockerfile
  src/ubuntu/18.04/cross/freebsd/13/hooks/post-build
  src/ubuntu/18.04/cross/freebsd/13/hooks/pre-build
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#959 Add git to alpine3.17-WithNode image
  src/alpine/3.19/WithNode/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#960 Add required packages to Alpine 3.19
  src/alpine/3.19/WithNode/amd64/Dockerfile
  src/alpine/3.19/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#957 Attempt to fix sourcebuild issues
  src/centos/stream9/Dockerfile
  src/fedora/39/amd64/Dockerfile
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/cross/arm64/Dockerfile
Labels: area-infrastructure, untriaged

#962 Add NO_UPDATE_NOTIFIER switch for Alpine
  src/alpine/3.19/WithNode/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#963 Suppress node version check in centos stream8 image
  src/centos/stream8/Dockerfile
Labels: area-documentation, untriaged

#961 Add freebsd 14
  src/cbl-mariner/2.0/cross/freebsd/14/amd64/Dockerfile
  src/cbl-mariner/2.0/cross/freebsd/14/arm64/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles, untriaged

#964 Apply nodejs changes to correct Ubuntu Dockerfile
  src/ubuntu/22.04/Dockerfile
  src/ubuntu/22.04/cross/arm64/Dockerfile
Labels: area-infrastructure, untriaged
