Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-03, with the labels that each got.

#975 Add mariner images for s390x and ppc64le
  src/cbl-mariner/2.0/cross/ppc64le/Dockerfile
  src/cbl-mariner/2.0/cross/s390x/Dockerfile
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/2.0/crossdeps/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-infrastructure, untriaged

#974 Add NodeJS to CBL mariner build containers
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
Labels: untriaged

#978 Move node installation to crossdeps image
  src/cbl-mariner/2.0/crossdeps-builder/Dockerfile
  src/cbl-mariner/2.0/crossdeps/Dockerfile
Labels: area-dockerfiles, untriaged

#979 symlink npm and npx
  src/cbl-mariner/2.0/crossdeps/Dockerfile
Labels: untriaged

#981 Add WithNode flavor for Alpine 3.18
  src/alpine/3.18/WithNode/amd64/Dockerfile
  src/alpine/3.18/amd64/Dockerfile
  src/alpine/manifest.json
Labels: untriaged

#976 Update to llvm 18 in Ubuntu 22.04 cross images
  src/ubuntu/22.04/crossdeps/Dockerfile
Labels: area-dockerfiles, untriaged

#982 Remove EOL Dockerfiles
  src/alpine/3.15/WithNode/amd64/Dockerfile
  src/alpine/3.15/amd64/Dockerfile
  src/alpine/3.15/helix/amd64/Dockerfile
  src/alpine/3.15/helix/arm32v7/Dockerfile
  src/alpine/3.15/helix/arm64v8/Dockerfile
  src/alpine/manifest.json
  src/cbl-mariner/1.0/helix/amd64/Dockerfile
  src/cbl-mariner/manifest.json
Labels: area-dockerfiles, untriaged

#984 Use .NET 1ES hosted pool for public builds
  eng/pipelines/stages/build-test-publish-repo.yml
Labels: area-infrastructure, untriaged

#985 Add LLDB to Mariner 2.0 image
  src/cbl-mariner/2.0/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#986 Remove Debian 10 Dockerfiles
  src/debian/10/helix/amd64/Dockerfile
  src/debian/10/helix/arm32v7/Dockerfile
  src/debian/10/helix/arm64v8/Dockerfile
  src/debian/manifest.json
Labels: area-dockerfiles, untriaged

#989 Add lldb-devel in mariner cross images
  src/cbl-mariner/2.0/crossdeps/Dockerfile
Labels: untriaged

#992 [wasm] Removing step provisioning emsdk from WebAssembly containers
  src/cbl-mariner/2.0/webassembly/Dockerfile
  src/ubuntu/20.04/webassembly/Dockerfile
Labels: area-infrastructure, untriaged
