Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2024-04, with the labels that each got.

#1000 Enable SHA1 signatures in CentOS Stream9
  src/centos/stream9/Dockerfile
Labels: area-infrastructure, untriaged

#1001 Update timeout for dotnet-buildtools-prereqs-mariner
  eng/pipelines/dotnet-buildtools-prereqs-mariner.yml
Labels: area-infrastructure, untriaged

#1006 Update mariner build timeout
  eng/pipelines/dotnet-buildtools-prereqs-mariner.yml
Labels: area-infrastructure, untriaged

#1007 Install libmsquic in CentOS Stream 9 image
  src/centos/stream9/helix/amd64/Dockerfile
Labels: untriaged, area-samples

#1009 Increase build timeout for "all" pipeline
  eng/pipelines/dotnet-buildtools-prereqs-all.yml
Labels: area-infrastructure, untriaged

#1010 Get centos:7 images updated
  eng/pipelines/dotnet-buildtools-prereqs-centos.yml
  src/centos/7/Dockerfile
  src/centos/7/rpmpkg/Dockerfile
  src/centos/7/rpmpkg/scl_enable
  src/centos/7/source-build/amd64/Dockerfile
  src/centos/manifest.json
Labels: area-infrastructure, untriaged

#1013 Install tar on cbl-mariner helix dockerfile
  src/cbl-mariner/2.0/helix/amd64/Dockerfile
Labels: area-dockerfiles, untriaged

#1012 Resolve gem install errors
  src/ubuntu/18.04/amd64/Dockerfile
  src/ubuntu/18.04/arm32v7/Dockerfile
  src/ubuntu/18.04/arm64v8/Dockerfile
  src/ubuntu/18.04/coredeps/Dockerfile
Labels: area-infrastructure, untriaged

#1014 Use Mariner not Ubuntu as armv6 host image
  src/cbl-mariner/2.0/cross/armv6/Dockerfile
  src/cbl-mariner/manifest.json
  src/ubuntu/20.04/cross/armv6/10/Dockerfile
  src/ubuntu/20.04/cross/armv6/10/hooks/post-build
  src/ubuntu/20.04/cross/armv6/10/hooks/pre-build
  src/ubuntu/manifest.json
Labels: area-dockerfiles, untriaged

#1027 Fix LLVM_VERSION in a few places
  src/azurelinux/3.0/cross/amd64-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm-net9.0/Dockerfile
  src/azurelinux/3.0/cross/arm64-net9.0/Dockerfile
  src/azurelinux/3.0/cross/x86-net9.0/Dockerfile
Labels: area-documentation, untriaged
