Repository dotnet/dotnet-buildtools-prereqs-docker, pull requests merged in 2025-01, with the labels that each got.

#1306 Add linux-loongarch64 images
  src/azurelinux/3.0/net10.0/cross/loongarch64-musl/Dockerfile
  src/azurelinux/3.0/net10.0/cross/loongarch64/Dockerfile
  src/azurelinux/3.0/net10.0/crossdeps-builder/amd64/Dockerfile
  src/azurelinux/manifest.json
Labels: area-dockerfiles, untriaged

#1308 Add a missing include dir
  src/azurelinux/3.0/net10.0/cross/loongarch64/Dockerfile
Labels: untriaged

#1307 Copy as helixbot user
  src/alpine/3.17/helix/Dockerfile
  src/alpine/3.18/helix/Dockerfile
  src/alpine/3.20/helix/Dockerfile
  src/alpine/3.21/helix/Dockerfile
  src/azurelinux/3.0/helix/Dockerfile
  src/centos-stream/10.0/helix/Dockerfile
  src/debian/12/helix/amd64/Dockerfile
  src/debian/12/helix/arm32v7/Dockerfile
  src/debian/12/helix/arm64v8/Dockerfile
  src/debian/13/helix/Dockerfile
  src/fedora/41/helix/Dockerfile
  src/ubuntu/24.04/helix/Dockerfile
  src/ubuntu/24.10/helix/Dockerfile
Labels: untriaged

#1309 Dummy change to retrigger the new arch build
  src/azurelinux/3.0/net10.0/cross/loongarch64-musl/Dockerfile
  src/azurelinux/3.0/net10.0/cross/loongarch64/Dockerfile
  src/azurelinux/3.0/net10.0/crossdeps-llvm/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1310 Revert "Dummy change to retrigger the new arch build"
  src/azurelinux/3.0/net10.0/cross/loongarch64-musl/Dockerfile
  src/azurelinux/3.0/net10.0/cross/loongarch64/Dockerfile
  src/azurelinux/3.0/net10.0/crossdeps-llvm/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1317 Azure Linux cross riscv64: Update debootstrap to 1.0.140
  src/azurelinux/3.0/net10.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net8.0/cross/riscv64/Dockerfile
  src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile
Labels: area-infrastructure, untriaged

#1319 Add GitHub issue labeler workflow
  .github/labeler-config.yml
  .github/workflows/labeler.yml
Labels: area-infrastructure, untriaged

#1278 Bumped NDK version to 27
  src/azurelinux/3.0/net9.0/android/amd64/Dockerfile
Labels: area-infrastructure, untriaged

#1295 Floating tag support doc
  lifecycle.md
Labels: area-infrastructure, untriaged
